Repository yzharko/spbspu-labs-2023-aap-master, pull requests merged in 2023-11, with the labels that each got.

#49 zheleznyakov.mark/P1
  zheleznyakov.mark/P1/main.cpp
  zheleznyakov.mark/P1/seqCounter.cpp
  zheleznyakov.mark/P1/seqCounter.hpp
Labels: .ok, 5/5

#41 khoroshkin.maksim/P1
  khoroshkin.maksim/P1/findmax.cpp
  khoroshkin.maksim/P1/findmax.hpp
  khoroshkin.maksim/P1/main.cpp
Labels: .ok, 5/5

#39 seryj.alexey/P1
  seryj.alexey/P1/Funcs.cpp
  seryj.alexey/P1/Funcs.hpp
  seryj.alexey/P1/main.cpp
Labels: 5/5

#73 miheev.egor/P1
  miheev.egor/P1/dividing_counter.cpp
  miheev.egor/P1/dividing_counter.hpp
  miheev.egor/P1/functions.cpp
  miheev.egor/P1/functions.hpp
  miheev.egor/P1/main.cpp
Labels: .ok, 5/5

#75 doroshenko.anna/P1
  doroshenko.anna/P1/findingCount.cpp
  doroshenko.anna/P1/findingCount.hpp
  doroshenko.anna/P1/main.cpp
Labels: .ok, 5/5

#33 tellez.aron/P1
  tellez.aron/P1/main.cpp
  tellez.aron/P1/seqCounter.cpp
  tellez.aron/P1/seqCounter.hpp
Labels: .ok, 5/5

#89 sukacheva.maria/P1
  sukacheva.maria/P1/main.cpp
  sukacheva.maria/P1/minCount.cpp
  sukacheva.maria/P1/minCount.hpp
Labels: .ok, 5/5

#110 reznikova.anna/P1
  reznikova.anna/P1/FindDecSeq.cpp
  reznikova.anna/P1/FindDecSeq.hpp
  reznikova.anna/P1/FindEqSeq.cpp
  reznikova.anna/P1/FindEqSeq.hpp
  reznikova.anna/P1/main.cpp
Labels: .ok, 5/5

#10 taskaev.matvei/P1
  taskaev.matvei/P1/findmaxCountNumbers.cpp
  taskaev.matvei/P1/findmaxCountNumbers.hpp
  taskaev.matvei/P1/main.cpp
Labels: .ok, 5/5

#108 shagieva.dinara/P1
  shagieva.dinara/P1/changeCounter.cpp
  shagieva.dinara/P1/changeCounter.hpp
  shagieva.dinara/P1/divCounter.cpp
  shagieva.dinara/P1/divCounter.hpp
  shagieva.dinara/P1/main.cpp
Labels: .ok, 5/5

#63 psarev.alexandr/P1
  psarev.alexandr/P1/main.cpp
  psarev.alexandr/P1/maxLen.cpp
  psarev.alexandr/P1/maxLen.hpp
Labels: .ok, 5/5

#86 popov.nikita/P1
  popov.nikita/P1/counter_minimums.cpp
  popov.nikita/P1/counter_minimums.hpp
  popov.nikita/P1/main.cpp
Labels: .ok, 5/5

#38 litsinger.ernest/P1
  litsinger.ernest/P1/main.cpp
  litsinger.ernest/P1/maxchetn.cpp
  litsinger.ernest/P1/maxchetn.hpp
Labels: .ok, 5/5, .joker

#74 sobolevsky.misha/P1
  sobolevsky.misha/P1/main.cpp
  sobolevsky.misha/P1/maxchetn.cpp
  sobolevsky.misha/P1/maxchetn.hpp
Labels: .ok, 3/5

#77 redko.arina/P1
  redko.arina/P1/findmaxima.cpp
  redko.arina/P1/findmaxima.hpp
  redko.arina/P1/main.cpp
Labels: .ok, 5/5

#76 kovshikov.nikita/P1
  kovshikov.nikita/P1/even_count.cpp
  kovshikov.nikita/P1/even_count.hpp
  kovshikov.nikita/P1/main.cpp
Labels: 5/5

#88 khomichenko.alisa/P1
  khomichenko.alisa/P1/FindingSubMax.cpp
  khomichenko.alisa/P1/FindingSubMax.hpp
  khomichenko.alisa/P1/main.cpp
Labels: .ok, 5/5

#145 Merkulov.daniil/P0
  merkulov.daniil/P0/main.cpp
Labels: .ok

#112 shapar.arseniy/P0
  shapar.arseniy/P0/main.cpp
Labels: .ok

#146 ankhbayar.battsolmon/P0
  ankhbayar.battsolmon/P0/main.cpp
Labels: .ok

#81 jirkov.vladimir/P1
  jirkov.vladimir/P1/findingCount.cpp
  jirkov.vladimir/P1/findingCount.hpp
  jirkov.vladimir/P1/main.cpp
Labels: .ok, 5/5

#103 panov.ilya/P1
  panov.ilya/P1/afterMaximum.cpp
  panov.ilya/P1/afterMaximum.hpp
  panov.ilya/P1/main.cpp
  panov.ilya/P1/moreThanPrevious.cpp
  panov.ilya/P1/moreThanPrevious.hpp
  panov.ilya/P1/numberOfSignChanges.cpp
  panov.ilya/P1/numberOfSignChanges.hpp
Labels: .ok, 4/5

#94 kaseev.andrey/P1
  kaseev.andrey/P1/Divisibility.hpp
  kaseev.andrey/P1/divisibility.cpp
  kaseev.andrey/P1/main.cpp
Labels: .ok, 4/5

#78 nikiforov.alexander/P1
  nikiforov.alexander/P1/CountMinSequence.hpp
  nikiforov.alexander/P1/FuncCountMinSequence.cpp
  nikiforov.alexander/P1/main.cpp
Labels: .ok, 4/5

#100 gorbunova.alena/P1
  gorbunova.alena/P1/evenNumber.cpp
  gorbunova.alena/P1/evenNumber.hpp
  gorbunova.alena/P1/findCount.cpp
  gorbunova.alena/P1/findCount.hpp
  gorbunova.alena/P1/main.cpp
Labels: .ok, 3/5, .derSchwarzePunkt

#149 ponomarev.viacheslav/P1
  ponomarev.viacheslav/P1/main.cpp
  ponomarev.viacheslav/P1/seqCounter.cpp
  ponomarev.viacheslav/P1/seqCounter.hpp
Labels: .ok, 5/5

#60 smolyakov.alexander/P0
  smolyakov.alexander/P0/main.cpp
Labels: .ok

#107 yartsev.viktor/p1
  yartsev.viktor/P1/main.cpp
  yartsev.viktor/P1/minInSequence.cpp
  yartsev.viktor/P1/minInSequence.hpp
  yartsev.viktor/P1/sequenceCounter.cpp
  yartsev.viktor/P1/sequenceCounter.hpp
Labels: .ok, 5/5

#45 malanin.nikita/P1
  malanin.nikita/P1/foo.cpp
  malanin.nikita/P1/foo.hpp
  malanin.nikita/P1/main.cpp
Labels: .ok, 3/5

#148 zhitnyj.dmitriy/P1
  zhitnyj.dmitriy/P1/funcEqlSeq.cpp
  zhitnyj.dmitriy/P1/funcEqlSeq.h
  zhitnyj.dmitriy/P1/funcSumDup.cpp
  zhitnyj.dmitriy/P1/funcSumDup.h
  zhitnyj.dmitriy/P1/main.cpp
Labels: 4/5

#182 shapar.arseniy/P1
  shapar.arseniy/P1/GRT_LSS.cpp
  shapar.arseniy/P1/GRT_LSS.hpp
  shapar.arseniy/P1/SUM_DUP.cpp
  shapar.arseniy/P1/SUM_DUP.hpp
  shapar.arseniy/P1/main.cpp
  shapar.arseniy/P1/var1.cpp
  shapar.arseniy/P1/var1.hpp
  shapar.arseniy/P1/var2.cpp
  shapar.arseniy/P1/var2.hpp
Labels: .ok, 4/5

#129 psarev.alexandr/P4
  psarev.alexandr/P1/maxLen.cpp
  psarev.alexandr/P4/checkMatrix.cpp
  psarev.alexandr/P4/checkMatrix.hpp
  psarev.alexandr/P4/inputMatrix.cpp
  psarev.alexandr/P4/inputMatrix.hpp
  psarev.alexandr/P4/main.cpp
Labels: .ok, 5/5

#79 mihalchenko.vladislav/P1
  mihalchenko.vladislav/P1/Counter.cpp
  mihalchenko.vladislav/P1/Counter.hpp
  mihalchenko.vladislav/P1/main.cpp
Labels: .ok, 4/5

#91 sadofeva.nastya/P1
  sadofeva.nastya/P1/Source.cpp
  sadofeva.nastya/P1/kolvo.cpp
  sadofeva.nastya/P1/kolvo.h
Labels: .ok, 3/5

#96 tokshen.harun/P1
  tokshen.harun/P1/functions.cpp
  tokshen.harun/P1/functions.hpp
  tokshen.harun/P1/main.cpp
Labels: .ok, 3/5

#152 Likhachev.aleksey/P1
  likhachev.aleksey/P1/main.cpp
  likhachev.aleksey/P1/sequence.cpp
  likhachev.aleksey/P1/sequence.hpp
Labels: .ok, 4/5

#118 doroshenko.anna/P4
  doroshenko.anna/P4/findingLocMax.cpp
  doroshenko.anna/P4/findingLocMax.hpp
  doroshenko.anna/P4/inputArray.cpp
  doroshenko.anna/P4/inputArray.hpp
  doroshenko.anna/P4/main.cpp
Labels: .ok, 5/5
