Repository yzharko/spbspu-labs-2023-aap-master, pull requests merged in 2023-10, with the labels that each got.

#1 zheleznyakov.mark/P0
  zheleznyakov.mark/P0/main.cpp
Labels: .ok

#4 tokshen.harun/P0
  tokshen.harun/P0/main.cpp
Labels: .ok

#5 bronson.charles/P0
  bronson.charles/P0/main.cpp
Labels: .ok

#6 litsinger.ernest/P0
  litsinger.ernest/P0/main.cpp
Labels: .ok

#13 tellez.aron/P0
  tellez.aron/P0/main.cpp
Labels: .ok

#14 psarev.alexandr/P0
  psarev.alexandr/P0/main.cpp
Labels: .ok

#12 khoroshkin.maksim/P0
  khoroshkin.maksim/P0/main.cpp
Labels: .ok

#18 maksimov.leonid/p0
  maksimov.leonid/p0/main.cpp
Labels: .ok

#8 panov.ilya/P0
  panov.ilya/P0/main.cpp
Labels: .ok

#17 miheev.egor/P0
  miheev.egor/P0/main.cpp
Labels: .ok

#19 mihalchenko.vladislav/P0
  mihalchenko.vladislav/P0/main.cpp
Labels: .ok

#7 malanin.nikita/P0
  malanin.nikita/P0/main.cpp
Labels: .ok

#26 kovshikov.nikita/P0
  kovshikov.nikita/P0/main.cpp
Labels: .ok, ВОИН

#28 popov.nikita/P0
  popov.nikita/P0/main.cpp
Labels: .ok

#29 susidko.fedor/P0
  susidko.fedor/P0/main.cpp
Labels: .ok

#22 anikanov.vladislav/P0
  anikanov.vladislav/P0/main.cpp
Labels: .ok

#34 sobolevsky.misha/P0
  sobolevsky.misha/P0/main.cpp
Labels: .ok

#25 seryj.alexey/P0
  seryj.alexey/P0/main.cpp
Labels: .ok

#37 redko.arina/P0
  redko.arina/P0/main.cpp
Labels: .ok

#40 proselkov.stanislav/P0
  proselkov.stanislav/P0/main.cpp
Labels: .ok

#32 anikanov.vladislav/P1
  anikanov.vladislav/P1/findCountMinimalMembers.cpp
  anikanov.vladislav/P1/findCountMinimalMembers.hpp
  anikanov.vladislav/P1/main.cpp
Labels: .ok, 5/5

#20 sadofeva.nastya/P0
  sadofeva.nastya/P0/main.cpp
Labels: .ok

#42 shagieva.dinara/P0
  shagieva.dinara/P0/main.cpp
Labels: .ok

#24 likhachev.aleksey/P0
  likhachev.aleksey/P0/main.cpp
Labels: .ok

#44 sukacheva.maria/P0
  sukacheva.maria/P0/main.cpp
Labels: .ok

#36 lisitsyna.yulia/P0
  lisitsyna.yulia/P0/main.cpp
Labels: .ok

#43 reznikova.anna/P0
  reznikova.anna/P0/main.cpp
Labels: .ok

#47 khomichenko.alisa/P0
  khomichenko.alisa/P0/main.cpp
Labels: .ok

#59 ponomarev.viacheslav/P0
  ponomarev.viacheslav/P0/main.cpp
Labels: .ok

#62 gorbunova.alena/P0
  gorbunova.alena/P0/main.cpp
Labels: .ok

#31 susidko.fedor/P1
  susidko.fedor/P1/funcs.cpp
  susidko.fedor/P1/funcs.h
  susidko.fedor/P1/main.cpp
Labels: .ok, 5/5

#58 batunov.roman/P0
  batunov.roman/P0/main.cpp
Labels: .ok

#72 hohlova.polina/P0
  hohlova.polina/P0/main.cpp
Labels: .ok

#52 ankhbayar.battsolmon/p0
  ankhbayar.battsolmon/p0/main.cpp
Labels: .ok

#53 kaseev.andrey/P0
  kaseev.andrey/P0/main.cpp
Labels: .ok

#61 yarstev.viktor/P0
  yartsev.viktor/P0/main.cpp
Labels: .ok

#69 zhitnyj.dmitriy/p0
  zhitnyj.dmitriy/P0/main.cpp
Labels: .ok
