Repository yzharko/spbspu-labs-2023-aap-master, pull requests merged in 2023-12, with the labels that each got.

#113 seryj.alexey/P4
  seryj.alexey/P4/fillArray.cpp
  seryj.alexey/P4/fillArray.hpp
  seryj.alexey/P4/main.cpp
  seryj.alexey/P4/smoothedMarix.cpp
  seryj.alexey/P4/smoothedMatrix.hpp
Labels: .ok, 5/5

#126 anikanov.vladislav/P4
  anikanov.vladislav/P4/arrayModifications.cpp
  anikanov.vladislav/P4/arrayModifications.h
  anikanov.vladislav/P4/check.cpp
  anikanov.vladislav/P4/check.h
  anikanov.vladislav/P4/errorsPrint.cpp
  anikanov.vladislav/P4/errorsPrint.h
  anikanov.vladislav/P4/inOutArray.cpp
  anikanov.vladislav/P4/inOutArray.h
  anikanov.vladislav/P4/main.cpp
Labels: .ok, 5/5

#120 taskaev.matvei/P4
  taskaev.matvei/P4/findCntLocMin.cpp
  taskaev.matvei/P4/findCntLocMin.hpp
  taskaev.matvei/P4/inputArray.cpp
  taskaev.matvei/P4/inputArray.hpp
  taskaev.matvei/P4/main.cpp
Labels: .ok, 5/5

#131 shagieva.dinara/P4
  shagieva.dinara/P4/findMaxColumn.cpp
  shagieva.dinara/P4/findMaxColumn.hpp
  shagieva.dinara/P4/main.cpp
  shagieva.dinara/P4/readMatrix.cpp
  shagieva.dinara/P4/readMatrix.hpp
Labels: .ok, 5/5

#92 maksimov.leonid/P1
  maksimov.leonid/P1/main.cpp
  maksimov.leonid/P1/sequaenceCounter.cpp
  maksimov.leonid/P1/sequaenceCounter.hpp
Labels: .ok, 3/5

#143 kaseev.andrey/p4
  kaseev.andrey/P4/InputOutput.cpp
  kaseev.andrey/P4/InputOutput.hpp
  kaseev.andrey/P4/main.cpp
  kaseev.andrey/P4/matrix.cpp
  kaseev.andrey/P4/matrix.hpp
Labels: .ok, 4/5

#114 miheev.egor/P4
  miheev.egor/P4/functions.cpp
  miheev.egor/P4/functions.hpp
  miheev.egor/P4/main.cpp
  miheev.egor/P4/matrix_methods.cpp
  miheev.egor/P4/matrix_methods.hpp
Labels: .ok, 5/5

#132 nikiforov.alexander/P4
  nikiforov.alexander/P4/CreateMatrix.cpp
  nikiforov.alexander/P4/CreateMatrix.hpp
  nikiforov.alexander/P4/inputMatrix.cpp
  nikiforov.alexander/P4/inputMatrix.hpp
  nikiforov.alexander/P4/main.cpp
Labels: .ok, 4/5

#135 popov.nikita/P4
  popov.nikita/P4/main.cpp
  popov.nikita/P4/maximumSumStat.cpp
  popov.nikita/P4/maximumSumStat.hpp
Labels: .ok, 3/5

#142 tellez.aron/P4
  tellez.aron/P4/getMinSum.cpp
  tellez.aron/P4/getMinSum.hpp
  tellez.aron/P4/main.cpp
  tellez.aron/P4/readMatrix.cpp
  tellez.aron/P4/readMatrix.hpp
Labels: .ok, 5/5

#116 mihalchenko.vladislav/P4
  mihalchenko.vladislav/P4/dopFunc.cpp
  mihalchenko.vladislav/P4/dopFunc.hpp
  mihalchenko.vladislav/P4/inputArray.cpp
  mihalchenko.vladislav/P4/inputArray.hpp
  mihalchenko.vladislav/P4/main.cpp
  mihalchenko.vladislav/P4/matrix.cpp
  mihalchenko.vladislav/P4/matrix.hpp
  mihalchenko.vladislav/P4/outputArray.cpp
  mihalchenko.vladislav/P4/outputArray.hpp
Labels: .ok, 3/5

#117 hohlova.polina/p4
  hohlova.polina/P4/inputArray.cpp
  hohlova.polina/P4/inputArray.hpp
  hohlova.polina/P4/main.cpp
  hohlova.polina/P4/matrix.cpp
  hohlova.polina/P4/matrix.hpp
Labels: .ok, 4/5

#119 zheleznyakov.mark/P4
  zheleznyakov.mark/P4/findMaxRowInMatrix.cpp
  zheleznyakov.mark/P4/functions.hpp
  zheleznyakov.mark/P4/main.cpp
  zheleznyakov.mark/P4/read.cpp
Labels: .ok, 4/5

#121 litsinger.ernest/P4
  litsinger.ernest/P4/functioninput.cpp
  litsinger.ernest/P4/functioninput.hpp
  litsinger.ernest/P4/main.cpp
  litsinger.ernest/P4/variantlogic.cpp
  litsinger.ernest/P4/variantlogic.hpp
Labels: .ok, 4/5

#123 sadofeva.nastya/P4
  sadofeva.nastya/P4/inputArray.cpp
  sadofeva.nastya/P4/inputArray.hpp
  sadofeva.nastya/P4/locMax.cpp
  sadofeva.nastya/P4/locMax.hpp
  sadofeva.nastya/P4/main.cpp
Labels: .ok, 4/5

#124 lisitsyna.yulia/P4
  lisitsyna.yulia/P4/input_ar.cpp
  lisitsyna.yulia/P4/input_ar.hpp
  lisitsyna.yulia/P4/main.cpp
  lisitsyna.yulia/P4/minS.cpp
  lisitsyna.yulia/P4/minS.hpp
Labels: .ok, 3/5

#127 kovshikov.nikita/P4
  kovshikov.nikita/P4/count_saddle.cpp
  kovshikov.nikita/P4/count_saddle.hpp
  kovshikov.nikita/P4/create_matrix.cpp
  kovshikov.nikita/P4/create_matrix.hpp
  kovshikov.nikita/P4/main.cpp
Labels: .ok, 5/5

#128 redko.arina/P4
  redko.arina/P4/countCols.cpp
  redko.arina/P4/countCols.hpp
  redko.arina/P4/inputArray.cpp
  redko.arina/P4/inputArray.hpp
  redko.arina/P4/main.cpp
Labels: .ok, 5/5

#134 jirkov.vladimir/P4
  jirkov.vladimir/P4/decreaseSpiralElements.cpp
  jirkov.vladimir/P4/decreaseSpiralElements.hpp
  jirkov.vladimir/P4/inputArray.cpp
  jirkov.vladimir/P4/inputArray.hpp
  jirkov.vladimir/P4/main.cpp
  jirkov.vladimir/P4/sumArrays.cpp
  jirkov.vladimir/P4/sumArrays.hpp
Labels: .ok, 4/5

#202 shapar.arseniy/P4
  shapar.arseniy/P4/Matrix.hpp
  shapar.arseniy/P4/main.cpp
  shapar.arseniy/P4/readMatrix.cpp
  shapar.arseniy/P4/readMatrix.hpp
Labels: .ok, 2/5

#137 sobolevsky.misha/p4
  sobolevsky.misha/P4/fillMatrix.cpp
  sobolevsky.misha/P4/fillMatrix.hpp
  sobolevsky.misha/P4/isTrianglMatrix.cpp
  sobolevsky.misha/P4/isTrianglMatrix.hpp
  sobolevsky.misha/P4/main.cpp
Labels: .ok, 5/5

#140 Maksimov.leonid/p4
  maksimov.leonid/P4/class.cpp
  maksimov.leonid/P4/class.hpp
  maksimov.leonid/P4/file.cpp
  maksimov.leonid/P4/file.hpp
  maksimov.leonid/P4/main.cpp
Labels: .ok, 3/5

#185 malanin.nikita/p4
  malanin.nikita/P4/input.txt
  malanin.nikita/P4/inputArray.cpp
  malanin.nikita/P4/inputArray.hpp
  malanin.nikita/P4/main.cpp
  malanin.nikita/P4/matrix.cpp
  malanin.nikita/P4/matrix.hpp
  malanin.nikita/P4/output.txt
Labels: .ok, 2/5

#193 Khomichenko.alisa/p4
  khomichenko.alisa/P4/incPer.cpp
  khomichenko.alisa/P4/incPer.hpp
  khomichenko.alisa/P4/inputArray.cpp
  khomichenko.alisa/P4/inputArray.hpp
  khomichenko.alisa/P4/main.cpp
  khomichenko.alisa/P4/spiralSub.cpp
  khomichenko.alisa/P4/spiralSub.hpp
Labels: .ok, 3/5

#196 zhitnyj.dmitriy/P4
  zhitnyj.dmitriy/P4/functionsMatrix.cpp
  zhitnyj.dmitriy/P4/functionsMatrix.h
  zhitnyj.dmitriy/P4/main.cpp
Labels: .ok, 2/5

#217 batunov.roman/P4
  batunov.roman/P4/freeMatrix.cpp
  batunov.roman/P4/freeMatrix.hpp
  batunov.roman/P4/longestCombin.cpp
  batunov.roman/P4/longestCombin.hpp
  batunov.roman/P4/main.cpp
  batunov.roman/P4/readMatrixFromFile.cpp
  batunov.roman/P4/readMatrixFromFile.hpp
  batunov.roman/P4/readMatrixFromFilee.cpp
  batunov.roman/P4/readMatrixFromFilee.hpp
  batunov.roman/P4/smoothMatrix.cpp
  batunov.roman/P4/smoothMatrix.hpp
  batunov.roman/P4/writeArrayToFile.cpp
  batunov.roman/P4/writeArrayToFile.hpp
  batunov.roman/P4/writeResultToFile.cpp
  batunov.roman/P4/writeResultToFile.hpp
Labels: .ok, 2/5

#190 ponomarev.viacheslav/P4
  ponomarev.viacheslav/P4/inputArray.cpp
  ponomarev.viacheslav/P4/inputArray.hpp
  ponomarev.viacheslav/P4/main.cpp
  ponomarev.viacheslav/P4/minSu.cpp
  ponomarev.viacheslav/P4/minSu.hpp
  ponomarev.viacheslav/P4/sedlElem.cpp
  ponomarev.viacheslav/P4/sedlElem.hpp
Labels: .ok, 5/5

#186 Likhachev.aleksey/p4
  likhachev.aleksey/P4/main.cpp
  likhachev.aleksey/P4/matrixActions.cpp
  likhachev.aleksey/P4/matrixActions.hpp
Labels: .ok, 4/5

#229 susidko.fedor/P4
  susidko.fedor/P4/inputArray.cpp
  susidko.fedor/P4/inputArray.hpp
  susidko.fedor/P4/main.cpp
  susidko.fedor/P4/matrix.cpp
  susidko.fedor/P4/matrix.hpp
Labels: .ok, 3/5

#172 psarev.alexandr/P3
  psarev.alexandr/P3/createLine.cpp
  psarev.alexandr/P3/createLine.hpp
  psarev.alexandr/P3/expandLine.cpp
  psarev.alexandr/P3/expandLine.hpp
  psarev.alexandr/P3/main.cpp
  psarev.alexandr/P3/readLine.cpp
  psarev.alexandr/P3/readLine.hpp
  psarev.alexandr/P4/main.cpp
Labels: .ok, 5/5

#183 seryj.alexey/P3
  seryj.alexey/P3/EQUAL_CHARS_FINDER.cpp
  seryj.alexey/P3/EQUAL_CHARS_FINDER.hpp
  seryj.alexey/P3/main.cpp
Labels: .ok, 4/5
