Repository yzharko/spbspu-labs-2023-aap-master, pull requests merged in 2024-02, with the labels that each got.

#138 yartsev.viktor/p4
  yartsev.viktor/P1/seqCounter.cpp
  yartsev.viktor/P1/seqCounter.hpp
  yartsev.viktor/P4/arrfuncs.cpp
  yartsev.viktor/P4/arrfuncs.hpp
  yartsev.viktor/P4/checkmatrix.cpp
  yartsev.viktor/P4/checkmatrix.hpp
  yartsev.viktor/P4/main.cpp
Labels: .ok, 2/5, .dopS

#256 rejepbayev.jasur/P0
  rejepbayev.jasur/P0/main.cpp
Labels: .ok

#252 susidko.fedor/P3
  susidko.fedor/P3/getString.cpp
  susidko.fedor/P3/getString.hpp
  susidko.fedor/P3/main.cpp
  susidko.fedor/P3/replaceAndCount.cpp
  susidko.fedor/P3/replaceAndCount.hpp
Labels: .ok, 4/5, .dopS

#248 malanin.nikita/P3
  malanin.nikita/P3/main.cpp
  malanin.nikita/P3/transform.cpp
  malanin.nikita/P3/transform.hpp
Labels: 2/5, .dopS

#245 malanin.nikita/T1
  malanin.nikita/P3/main.cpp
  malanin.nikita/P3/transform.cpp
  malanin.nikita/P3/transform.hpp
  malanin.nikita/T1/base-types.hpp
  malanin.nikita/T1/main.cpp
  malanin.nikita/T1/rectangle.cpp
  malanin.nikita/T1/rectangle.hpp
  malanin.nikita/T1/shape.hpp
  malanin.nikita/T1/triangle.cpp
  malanin.nikita/T1/triangle.hpp
Labels: 2/5, .dopS

#260 tokshen.harun/P3
  tokshen.harun/P3/lat_two.cpp
  tokshen.harun/P3/lat_two.hpp
  tokshen.harun/P3/main.cpp
  tokshen.harun/P3/upplow.cpp
  tokshen.harun/P3/upplow.hpp
Labels: .ok, 2/5
