Repository yzharko/spbspu-labs-2023-aap-master, pull requests merged in 2024-01, with the labels that each got.

#154 panov.ilya/P3
  panov.ilya/P3/function.cpp
  panov.ilya/P3/function.hpp
  panov.ilya/P3/main.cpp
Labels: .ok, 2/5

#155 hohlova.polina/p3
  hohlova.polina/P3/findCommonChars.cpp
  hohlova.polina/P3/findCommonChars.hpp
  hohlova.polina/P3/main.cpp
  hohlova.polina/P3/readLine.cpp
  hohlova.polina/P3/readLine.hpp
Labels: .ok, 2/5

#156 redko.arina/P3
  redko.arina/P3/buildWithoutInt.cpp
  redko.arina/P3/buildWithoutInt.hpp
  redko.arina/P3/expandString.cpp
  redko.arina/P3/expandString.hpp
  redko.arina/P3/getString.cpp
  redko.arina/P3/getString.hpp
  redko.arina/P3/main.cpp
Labels: .ok, 5/5

#158 doroshenko.anna/P3
  doroshenko.anna/P3/functions.cpp
  doroshenko.anna/P3/functions.hpp
  doroshenko.anna/P3/main.cpp
Labels: .ok, 3/5

#159 reznikova.anna/P3
  reznikova.anna/P3/ExcludeSecString.cpp
  reznikova.anna/P3/ExcludeSecString.hpp
  reznikova.anna/P3/InputString.cpp
  reznikova.anna/P3/InputString.hpp
  reznikova.anna/P3/main.cpp
Labels: .ok, 3/5

#160 khoroshkin.maksim/P3
  khoroshkin.maksim/P3/excsndLine.cpp
  khoroshkin.maksim/P3/excsndLine.hpp
  khoroshkin.maksim/P3/frqtopLine.cpp
  khoroshkin.maksim/P3/frqtopLine.hpp
  khoroshkin.maksim/P3/main.cpp
  khoroshkin.maksim/P3/setLine.cpp
  khoroshkin.maksim/P3/setLine.hpp
Labels: .ok, 3/5

#161 kaseev.andrey/P3
  kaseev.andrey/P3/WorkWithString.cpp
  kaseev.andrey/P3/WorkWithString.hpp
  kaseev.andrey/P3/main.cpp
Labels: .ok, 3/5

#162 shagieva.dinara/P3
  shagieva.dinara/P3/main.cpp
  shagieva.dinara/P3/readString.cpp
  shagieva.dinara/P3/readString.hpp
  shagieva.dinara/P3/uppLow.cpp
  shagieva.dinara/P3/uppLow.hpp
Labels: .ok, 5/5

#163 kovshikov.nikita/P3
  kovshikov.nikita/P3/dgt_snd.cpp
  kovshikov.nikita/P3/dgt_snd.hpp
  kovshikov.nikita/P3/main.cpp
  kovshikov.nikita/P3/read_input.cpp
  kovshikov.nikita/P3/read_input.hpp
  kovshikov.nikita/P3/shr_sym.cpp
  kovshikov.nikita/P3/shr_sym.hpp
Labels: .ok, 4/5

#166 sukacheva.maria/P3
  sukacheva.maria/P3/formingNewString.cpp
  sukacheva.maria/P3/formingNewString.hpp
  sukacheva.maria/P3/inputString.cpp
  sukacheva.maria/P3/inputString.hpp
  sukacheva.maria/P3/main.cpp
Labels: .ok, 3/5

#167 smolyakov.alexander/P3
  smolyakov.alexander/P3/dynamicStringReader.cpp
  smolyakov.alexander/P3/dynamicStringReader.hpp
  smolyakov.alexander/P3/main.cpp
  smolyakov.alexander/P3/repeatingDigitsCheck.cpp
  smolyakov.alexander/P3/repeatingDigitsCheck.hpp
Labels: .ok, 3/5

#168 sadofeva.nastya/P3
  sadofeva.nastya/P3/funct.cpp
  sadofeva.nastya/P3/funct.hpp
  sadofeva.nastya/P3/main.cpp
Labels: .ok, 2/5

#170 anikanov.vladislav/P3
  anikanov.vladislav/P3/REPDGT.cpp
  anikanov.vladislav/P3/REPDGT.h
  anikanov.vladislav/P3/RMVVOW.cpp
  anikanov.vladislav/P3/RMVVOW.h
  anikanov.vladislav/P3/input.cpp
  anikanov.vladislav/P3/input.h
  anikanov.vladislav/P3/main.cpp
Labels: .ok, 4/5

#171 jirkov.vladimir/P3
  jirkov.vladimir/P3/checkDuplicatesChars.cpp
  jirkov.vladimir/P3/checkDuplicatesChars.hpp
  jirkov.vladimir/P3/inputString.cpp
  jirkov.vladimir/P3/inputString.hpp
  jirkov.vladimir/P3/main.cpp
Labels: .ok, 5/5

#173 mihalchenko.vladislav/P3
  mihalchenko.vladislav/P3/dinString.cpp
  mihalchenko.vladislav/P3/dinString.hpp
  mihalchenko.vladislav/P3/main.cpp
Labels: .ok, 2/5

#174 taskaev.matvei/P3
  taskaev.matvei/P3/findRplSym.cpp
  taskaev.matvei/P3/findRplSym.hpp
  taskaev.matvei/P3/formingString.cpp
  taskaev.matvei/P3/formingString.hpp
  taskaev.matvei/P3/main.cpp
  taskaev.matvei/P3/readingString.cpp
  taskaev.matvei/P3/readingString.hpp
Labels: .ok, 4/5

#178 Likhachev.aleksey/P3
  likhachev.aleksey/P3/main.cpp
  likhachev.aleksey/P3/sequences.cpp
  likhachev.aleksey/P3/sequences.hpp
Labels: .ok, 3/5

#179 gorbunova.alena/P3
  gorbunova.alena/P3/function.cpp
  gorbunova.alena/P3/function.hpp
  gorbunova.alena/P3/main.cpp
Labels: .ok, 2/5

#157 litsinger.ernest/P3
  litsinger.ernest/P3/function.cpp
  litsinger.ernest/P3/function.hpp
  litsinger.ernest/P3/main.cpp
Labels: .ok, 2/5

#191 tellez.aron/P3
  tellez.aron/P3/hasRepeatedChars.cpp
  tellez.aron/P3/hasRepeatedChars.hpp
  tellez.aron/P3/main.cpp
  tellez.aron/P3/readDynamicString.cpp
  tellez.aron/P3/readDynamicString.hpp
  tellez.aron/P3/remplaceChar.cpp
  tellez.aron/P3/remplaceChar.hpp
Labels: .ok, 4/5

#197 nikiforov.alexander/P3
  nikiforov.alexander/P3/addSizeLine.cpp
  nikiforov.alexander/P3/addSizeLine.hpp
  nikiforov.alexander/P3/comparisonLine.cpp
  nikiforov.alexander/P3/comparisonLine.hpp
  nikiforov.alexander/P3/main.cpp
  nikiforov.alexander/P3/readLine.cpp
  nikiforov.alexander/P3/readLine.hpp
Labels: .ok, 3/5

#231 khomichenko.alisa/P3
  khomichenko.alisa/P3/main.cpp
  khomichenko.alisa/P3/readString.cpp
  khomichenko.alisa/P3/readString.hpp
  khomichenko.alisa/P3/varFunc.cpp
  khomichenko.alisa/P3/varFunc.hpp
Labels: .ok, 3/5

#232 zhitnyj.dmytriy/P3
  zhitnyj.dmitriy/P3/functionDgtSnd.cpp
  zhitnyj.dmitriy/P3/functionDgtSnd.h
  zhitnyj.dmitriy/P3/functionSeqSym.cpp
  zhitnyj.dmitriy/P3/functionSeqSym.h
  zhitnyj.dmitriy/P3/functionStrRead.cpp
  zhitnyj.dmitriy/P3/functionStrRead.h
  zhitnyj.dmitriy/P3/main.cpp
Labels: .ok, 3/5

#238 batunov.roman/P3
  batunov.roman/P3/commonSymbols.cpp
  batunov.roman/P3/commonSymbols.hpp
  batunov.roman/P3/main.cpp
  batunov.roman/P3/untils.cpp
  batunov.roman/P3/untils.hpp
Labels: .ok, 2/5

#177 Maksimov.leonid/p3
  maksimov.leonid/P3/comparison.cpp
  maksimov.leonid/P3/comparison.hpp
  maksimov.leonid/P3/delvow.cpp
  maksimov.leonid/P3/delvow.hpp
  maksimov.leonid/P3/delzero.cpp
  maksimov.leonid/P3/delzero.hpp
  maksimov.leonid/P3/main.cpp
  maksimov.leonid/P3/newarr.cpp
  maksimov.leonid/P3/newarr.hpp
Labels: .ok, 3/5

#230 jirkov.vladimir/T1
  jirkov.vladimir/T1/base-types.hpp
  jirkov.vladimir/T1/concave.cpp
  jirkov.vladimir/T1/concave.hpp
  jirkov.vladimir/T1/diamond.cpp
  jirkov.vladimir/T1/diamond.hpp
  jirkov.vladimir/T1/main.cpp
  jirkov.vladimir/T1/rectangle.cpp
  jirkov.vladimir/T1/rectangle.hpp
  jirkov.vladimir/T1/shape.hpp
Labels: .ok, .derSchwarzePunkt, 2/5

#247 anikanov.vladislav/T1
  anikanov.vladislav/T1/base-types-ff.hpp
  anikanov.vladislav/T1/base-types.cpp
  anikanov.vladislav/T1/base-types.hpp
  anikanov.vladislav/T1/complexquad.cpp
  anikanov.vladislav/T1/complexquad.hpp
  anikanov.vladislav/T1/compositeShape.cpp
  anikanov.vladislav/T1/compositeShape.hpp
  anikanov.vladislav/T1/main-ext.cpp
  anikanov.vladislav/T1/main-ext.hpp
  anikanov.vladislav/T1/main.cpp
  anikanov.vladislav/T1/rectangle.cpp
  anikanov.vladislav/T1/rectangle.hpp
  anikanov.vladislav/T1/shape.hpp
  anikanov.vladislav/T1/square.cpp
  anikanov.vladislav/T1/square.hpp
Labels: .ok, 3/5

#204 Sobolevsky.misha/t1
  sobolevsky.misha/T1/base-types.hpp
  sobolevsky.misha/T1/diamond.cpp
  sobolevsky.misha/T1/diamond.hpp
  sobolevsky.misha/T1/main.cpp
  sobolevsky.misha/T1/parallelogram.cpp
  sobolevsky.misha/T1/parallelogram.hpp
  sobolevsky.misha/T1/rectangle.cpp
  sobolevsky.misha/T1/rectangle.hpp
  sobolevsky.misha/T1/shape.hpp
Labels: .ok, 3/5

#200 khoroshkin.maksim/T1
  khoroshkin.maksim/T1/base-types.hpp
  khoroshkin.maksim/T1/circle.cpp
  khoroshkin.maksim/T1/circle.hpp
  khoroshkin.maksim/T1/complexquad.cpp
  khoroshkin.maksim/T1/complexquad.hpp
  khoroshkin.maksim/T1/helpfulFuncs.cpp
  khoroshkin.maksim/T1/helpfulFuncs.hpp
  khoroshkin.maksim/T1/main.cpp
  khoroshkin.maksim/T1/rectangle.cpp
  khoroshkin.maksim/T1/rectangle.hpp
  khoroshkin.maksim/T1/shape.cpp
  khoroshkin.maksim/T1/shape.hpp
Labels: .ok, 4/5

#208 sukacheva.maria/T1
  sukacheva.maria/T1/base-types.hpp
  sukacheva.maria/T1/circle.cpp
  sukacheva.maria/T1/circle.hpp
  sukacheva.maria/T1/equalityOfPoints.cpp
  sukacheva.maria/T1/equalityOfPoints.hpp
  sukacheva.maria/T1/main.cpp
  sukacheva.maria/T1/parallelogram.cpp
  sukacheva.maria/T1/parallelogram.hpp
  sukacheva.maria/T1/rectangle.cpp
  sukacheva.maria/T1/rectangle.hpp
  sukacheva.maria/T1/scaleFunc.cpp
  sukacheva.maria/T1/scaleFunc.hpp
  sukacheva.maria/T1/shape.cpp
  sukacheva.maria/T1/shape.hpp
Labels: .ok, 4/5

#228 shagieva.dinara/T1
  shagieva.dinara/T1/base-types.hpp
  shagieva.dinara/T1/complexquad.cpp
  shagieva.dinara/T1/complexquad.hpp
  shagieva.dinara/T1/dataFunctions.cpp
  shagieva.dinara/T1/dataFunctions.hpp
  shagieva.dinara/T1/main.cpp
  shagieva.dinara/T1/rectangle.cpp
  shagieva.dinara/T1/rectangle.hpp
  shagieva.dinara/T1/regular.cpp
  shagieva.dinara/T1/regular.hpp
  shagieva.dinara/T1/resourceFunctions.cpp
  shagieva.dinara/T1/resourceFunctions.hpp
  shagieva.dinara/T1/shape.cpp
  shagieva.dinara/T1/shape.hpp
Labels: .ok, 4/5

#201 redko.arina/T1
  redko.arina/T1/base-types.hpp
  redko.arina/T1/concave.cpp
  redko.arina/T1/concave.hpp
  redko.arina/T1/main.cpp
  redko.arina/T1/parallelogram.cpp
  redko.arina/T1/parallelogram.hpp
  redko.arina/T1/rectangle.cpp
  redko.arina/T1/rectangle.hpp
  redko.arina/T1/shape.cpp
  redko.arina/T1/shape.hpp
  redko.arina/T1/shapeProcessing.cpp
  redko.arina/T1/shapeProcessing.hpp
Labels: .ok, 4/5

#203 hohlova.polina/t1
  hohlova.polina/T1/base-types.hpp
  hohlova.polina/T1/main.cpp
  hohlova.polina/T1/rectangle.cpp
  hohlova.polina/T1/rectangle.hpp
  hohlova.polina/T1/shape.hpp
  hohlova.polina/T1/square.cpp
  hohlova.polina/T1/square.hpp
  hohlova.polina/T1/triangle.cpp
  hohlova.polina/T1/triangle.hpp
Labels: .ok, 2/5

#213 sadofeva.nastya/T1
  sadofeva.nastya/T1/base-tapes.hpp
  sadofeva.nastya/T1/complexquad.cpp
  sadofeva.nastya/T1/complexquad.hpp
  sadofeva.nastya/T1/ellipse.cpp
  sadofeva.nastya/T1/ellipse.hpp
  sadofeva.nastya/T1/helpfunct.cpp
  sadofeva.nastya/T1/helpfunct.hpp
  sadofeva.nastya/T1/main.cpp
  sadofeva.nastya/T1/rectangle.cpp
  sadofeva.nastya/T1/rectangle.hpp
  sadofeva.nastya/T1/shape.hpp
Labels: .ok, 2/5

#221 miheev.egor/T1
  miheev.egor/T1/base-types.hpp
  miheev.egor/T1/figuresValidating.cpp
  miheev.egor/T1/figuresValidating.hpp
  miheev.egor/T1/geometricalMethods.cpp
  miheev.egor/T1/geometricalMethods.hpp
  miheev.egor/T1/main.cpp
  miheev.egor/T1/parallelogram.cpp
  miheev.egor/T1/parallelogram.hpp
  miheev.egor/T1/printFunctions.cpp
  miheev.egor/T1/printFunctions.hpp
  miheev.egor/T1/rectangle.cpp
  miheev.egor/T1/rectangle.hpp
  miheev.egor/T1/shape.hpp
  miheev.egor/T1/triangle.cpp
  miheev.egor/T1/triangle.hpp
Labels: .ok, 3/5

#223 mihalchenko.vladislav/T1
  mihalchenko.vladislav/T1/base-types.hpp
  mihalchenko.vladislav/T1/funcInOut.cpp
  mihalchenko.vladislav/T1/funcInOut.hpp
  mihalchenko.vladislav/T1/main.cpp
  mihalchenko.vladislav/T1/poligon.cpp
  mihalchenko.vladislav/T1/poligon.hpp
  mihalchenko.vladislav/T1/rectangle.cpp
  mihalchenko.vladislav/T1/rectangle.hpp
  mihalchenko.vladislav/T1/shape.hpp
  mihalchenko.vladislav/T1/square.cpp
  mihalchenko.vladislav/T1/square.hpp
Labels: .ok, 2/5

#224 kaseev.andrey/T1
  kaseev.andrey/T1/ base-types.hpp
  kaseev.andrey/T1/Ellipse.cpp
  kaseev.andrey/T1/Ellipse.hpp
  kaseev.andrey/T1/Parallelogram.cpp
  kaseev.andrey/T1/Parallelogram.hpp
  kaseev.andrey/T1/main.cpp
  kaseev.andrey/T1/rectangle.cpp
  kaseev.andrey/T1/rectangle.hpp
  kaseev.andrey/T1/shape.hpp
Labels: .ok, 2/5

#225 gorbunova.alena/T1
  gorbunova.alena/T1/base-types.hpp
  gorbunova.alena/T1/rectangle.cpp
  gorbunova.alena/T1/rectangle.hpp
  gorbunova.alena/T1/shape.hpp
Labels: .ok, 2/5

#233 zhitnyj.dmytriy/T1
  zhitnyj.dmitriy/T1/base-types.hpp
  zhitnyj.dmitriy/T1/complex-quad.cpp
  zhitnyj.dmitriy/T1/complex-quad.hpp
  zhitnyj.dmitriy/T1/composite-shape.cpp
  zhitnyj.dmitriy/T1/composite-shape.hpp
  zhitnyj.dmitriy/T1/main.cpp
  zhitnyj.dmitriy/T1/rectangle.cpp
  zhitnyj.dmitriy/T1/rectangle.hpp
  zhitnyj.dmitriy/T1/ring.cpp
  zhitnyj.dmitriy/T1/ring.hpp
  zhitnyj.dmitriy/T1/shape.hpp
  zhitnyj.dmitriy/T1/triangle.cpp
  zhitnyj.dmitriy/T1/triangle.hpp
Labels: .ok, 2/5

#215 litsinger.ernest/T1
  litsinger.ernest/T1/BaseTypes.cpp
  litsinger.ernest/T1/BaseTypes.hpp
  litsinger.ernest/T1/Main.cpp
  litsinger.ernest/T1/Rectangle.cpp
  litsinger.ernest/T1/Rectangle.hpp
  litsinger.ernest/T1/Ring.cpp
  litsinger.ernest/T1/Ring.hpp
  litsinger.ernest/T1/Shape.hpp
  litsinger.ernest/T1/Square.cpp
  litsinger.ernest/T1/Square.hpp
Labels: .ok, 2/5

#212 doroshenko.anna/T1
  doroshenko.anna/T1/base-types.hpp
  doroshenko.anna/T1/concave.cpp
  doroshenko.anna/T1/concave.hpp
  doroshenko.anna/T1/main.cpp
  doroshenko.anna/T1/rectangle.cpp
  doroshenko.anna/T1/rectangle.hpp
  doroshenko.anna/T1/shape.hpp
  doroshenko.anna/T1/triangle.cpp
  doroshenko.anna/T1/triangle.hpp
Labels: .ok, 3/5

#195 Likhachev.aleksey/T1
  likhachev.aleksey/T1/base-types.cpp
  likhachev.aleksey/T1/base-types.hpp
  likhachev.aleksey/T1/main.cpp
  likhachev.aleksey/T1/parallelogram.cpp
  likhachev.aleksey/T1/parallelogram.hpp
  likhachev.aleksey/T1/rectangle.cpp
  likhachev.aleksey/T1/rectangle.hpp
  likhachev.aleksey/T1/ring.cpp
  likhachev.aleksey/T1/ring.hpp
  likhachev.aleksey/T1/shape-functions.cpp
  likhachev.aleksey/T1/shape-functions.hpp
  likhachev.aleksey/T1/shape.hpp
  likhachev.aleksey/T1/shapes.hpp
  likhachev.aleksey/T1/utils.hpp
Labels: .ok, 3/5

#211 psarev.alexandr/T1
  psarev.alexandr/T1/base-types.hpp
  psarev.alexandr/T1/funcsDepot.cpp
  psarev.alexandr/T1/funcsDepot.hpp
  psarev.alexandr/T1/main.cpp
  psarev.alexandr/T1/rectangle.cpp
  psarev.alexandr/T1/rectangle.hpp
  psarev.alexandr/T1/ring.cpp
  psarev.alexandr/T1/ring.hpp
  psarev.alexandr/T1/shape.hpp
  psarev.alexandr/T1/triangle.cpp
  psarev.alexandr/T1/triangle.hpp
Labels: .ok, 3/5

#205 reznikova.anna/T1
  reznikova.anna/T1/array_functions.cpp
  reznikova.anna/T1/array_functions.hpp
  reznikova.anna/T1/base-types.hpp
  reznikova.anna/T1/main.cpp
  reznikova.anna/T1/rectangle.cpp
  reznikova.anna/T1/rectangle.hpp
  reznikova.anna/T1/regular.cpp
  reznikova.anna/T1/regular.hpp
  reznikova.anna/T1/ring.cpp
  reznikova.anna/T1/ring.hpp
  reznikova.anna/T1/scale_figures.cpp
  reznikova.anna/T1/scale_figures.hpp
  reznikova.anna/T1/set_figures.cpp
  reznikova.anna/T1/set_figures.hpp
  reznikova.anna/T1/shape.hpp
  reznikova.anna/T1/string_process.cpp
  reznikova.anna/T1/string_process.hpp
Labels: .ok, 3/5

#218 kovshikov.nikita/T1
  kovshikov.nikita/T1/base-types.hpp
  kovshikov.nikita/T1/main.cpp
  kovshikov.nikita/T1/polygon.cpp
  kovshikov.nikita/T1/polygon.hpp
  kovshikov.nikita/T1/rectangle.cpp
  kovshikov.nikita/T1/rectangle.hpp
  kovshikov.nikita/T1/shape.hpp
  kovshikov.nikita/T1/triangle.cpp
  kovshikov.nikita/T1/triangle.hpp
Labels: .ok, 2/5

#219 maksimov.leonid/T1
  maksimov.leonid/T1/base-types.hpp
  maksimov.leonid/T1/main.cpp
  maksimov.leonid/T1/rectangle.cpp
  maksimov.leonid/T1/rectangle.hpp
  maksimov.leonid/T1/shape.hpp
  maksimov.leonid/T1/square.cpp
  maksimov.leonid/T1/square.hpp
Labels: .ok, 2/5

#220 zheleznyakov.mark/T1
  zheleznyakov.mark/T1/base-types.hpp
  zheleznyakov.mark/T1/diamond.cpp
  zheleznyakov.mark/T1/diamond.hpp
  zheleznyakov.mark/T1/length.cpp
  zheleznyakov.mark/T1/length.hpp
  zheleznyakov.mark/T1/main.cpp
  zheleznyakov.mark/T1/output.cpp
  zheleznyakov.mark/T1/output.hpp
  zheleznyakov.mark/T1/rectangle.cpp
  zheleznyakov.mark/T1/rectangle.hpp
  zheleznyakov.mark/T1/regular.cpp
  zheleznyakov.mark/T1/regular.hpp
  zheleznyakov.mark/T1/shape.hpp
  zheleznyakov.mark/T1/validation.cpp
  zheleznyakov.mark/T1/validation.hpp
Labels: .ok, 2/5

#222 taskaev.matvei/T1
  taskaev.matvei/T1/Shape.hpp
  taskaev.matvei/T1/baseTypes.hpp
  taskaev.matvei/T1/concave.cpp
  taskaev.matvei/T1/concave.hpp
  taskaev.matvei/T1/ellipse.cpp
  taskaev.matvei/T1/ellipse.hpp
  taskaev.matvei/T1/main.cpp
  taskaev.matvei/T1/rectangle.cpp
  taskaev.matvei/T1/rectangle.hpp
Labels: .ok, 2/5

#250 seryj.alexey/T1
  seryj.alexey/T1/base-types.hpp
  seryj.alexey/T1/composite_shape.cpp
  seryj.alexey/T1/composite_shape.hpp
  seryj.alexey/T1/input_output.cpp
  seryj.alexey/T1/input_output.hpp
  seryj.alexey/T1/main.cpp
  seryj.alexey/T1/rectangle.cpp
  seryj.alexey/T1/rectangle.hpp
  seryj.alexey/T1/regular.cpp
  seryj.alexey/T1/regular.hpp
  seryj.alexey/T1/shape.hpp
  seryj.alexey/T1/square.cpp
  seryj.alexey/T1/square.hpp
  seryj.alexey/T1/vector.hpp
Labels: .ok, 3/5
